workspace:
  base: /srv/apps
  path: juglans

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - node_modules
    volumes:
      - /srv/apps/juglans:/cache
  
  master-build:
    image: node:8.1.4-alpine
    commands:
      - npm install --registry=https://registry.npm.taobao.org
      - npm install pkg apidoc -g
      - CONFIG_ENV=dev npm run build
    when:
      branch: master
      event: [push, pull_request]

  rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
        - node_modules
      volumes:
        - /srv/apps/juglans:/cache

